services:
  # Consolidated Web Service (Backend + Frontend together)
  - type: web
    name: navoday
    env: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend --include=dev && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # User will input Atlas link on Render dashboard
      - key: JWT_SECRET
        sync: false # User will input secret on Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        value: daulyz7fl
      - key: CLOUDINARY_API_KEY
        value: 922436663281344
      - key: CLOUDINARY_API_SECRET
        value: rcTYG6X0QIolmq5TD5CjNHHZqPc
      - key: CLOUDINARY_URL
        value: cloudinary://922436663281344:rcTYG6X0QIolmq5TD5CjNHHZqPc@daulyz7fl
